image:
  file: .gitpod.Dockerfile
ports:
  - name: Web App
    description: The main application web server
    port: 6000
    onOpen: ignore
    visibility : public
tasks:
  - command: gunicorn app:app --bind 0.0.0.0:5500 --workers 2 --threads 2 --timeout 100

